notifications:
  slack:
    secure: twDT06GAiu0jsKizow7TcghZj70KbuuTrlo02QGmbSxBk2rJfsXSrHAsA3+s/9Q4mudENk6na7fs1aPCxz+u2etUGp+2PaJKVKR5n3jrNNt3SnYeWsBgVo7o7H1aLXatX3a+TdPXh1F5gQ4Ycr93nTYbW/077jsOholwbOHDZE3VcU9dzNPwFaEvhrDbr/ei3tef0ZiM1qxIad74TgwWMKClwai3I7HCVkZOPsyV+ve6cdIJ8Dt47JzFUHSW3SZuoe5Kywxvp0VvMo/QAJw95y3edNafx4EXHwbaN71rpGWSJXIKSZzcSQalZJ9DxGYspIBkWvGsNuQRzG9CzIoNQK10iERlIVC5vKDfKX22gayOQPSDkswJzIduylBUC8zdTPCndXyNEM/Lrj6hg+ksFWN58vYNPgfUeiga7X+LV5HytftsMFW+xx2kbnGeU8doGeX8Q8G7h9OIkHCTTG7R0ldYMIqTm8YJGPkRIv4OReC5ZOhiZD+wSg4KQ0wmMeRi+hyn+I5UPnKEOHAIN8FmLNCZFbgr1wuPFp9xnJIOcumQnQVZ2t6vk6IjIbwhYPWCnf7Sr4BvJxE8eyiLrEaXK0FiPb3My9wK9tLFjj1zdD7e4+SLq+WFMeCxp2eXOGF0Bu+2VK2tGjgWhaudaIpjbRQAAQ5nPa43h16NruEvNWI=

cache:
  directories:
    - node_modules

addons:
  sauce_connect: true

matrix:
  include:
  - name: "iOS Build & Test"
    language: objective-c
    sudo: false
    os: osx
    osx_image: xcode10.1

    before_install:
    - export LANG=en_US.UTF-8

    install:
    - npm install

    script:
    - npm run testjs &&
      npm run updatecert &&
      scripts/build-test-app.sh --ios --emulator &&
      scripts/upload-saucelabs.sh --ios &&
      scripts/test-app.sh --ios --emulator;

  - name: "Android Build & Test"
    language: android
    sudo : required

    android:
      components:
        - platform-tools
        - build-tools-28.0.3
        - android-27
        - extra-android-support
        - extra-android-m2repository
        - extra-google-m2repository

    before_install:
    - export LANG=en_US.UTF-8 &&
      curl -sL https://deb.nodesource.com/setup_8.x | sudo -E bash - &&
      sudo apt-get install -y nodejs

    install:
    - npm install

    script:
    - npm run testjs &&
      npm run updatecert &&
      scripts/build-test-app.sh --android --emulator &&
      scripts/upload-saucelabs.sh --android &&
      scripts/test-app.sh --android --emulator;
